<?php

return [
    'KR' => 'Asia/Seoul',
    'JP' => 'Asia/Tokyo',
    'CN' => 'Asia/Shanghai',
    'TW' => 'Asia/Taipei',
    'HK' => 'Asia/Hong_Kong',
    'SG' => 'Asia/Singapore',
    'TH' => 'Asia/Bangkok',
    'VN' => 'Asia/Ho_Chi_Minh',
    'PH' => 'Asia/Manila',
    'ID' => 'Asia/Jakarta',
    'IN' => 'Asia/Kolkata',
    'AE' => 'Asia/Dubai',
    'SA' => 'Asia/Riyadh',
    'TR' => 'Europe/Istanbul',
    'DE' => 'Europe/Berlin',
    'FR' => 'Europe/Paris',
    'GB' => 'Europe/London',
    'IT' => 'Europe/Rome',
    'ES' => 'Europe/Madrid',
    'NL' => 'Europe/Amsterdam',
    'RU' => 'Europe/Moscow',
    'AU' => 'Australia/Sydney',
    'NZ' => 'Pacific/Auckland',
    'CA' => 'America/Toronto',
    'US' => 'America/New_York',
    'MX' => 'America/Mexico_City',
    'BR' => 'America/Sao_Paulo',
    'AR' => 'America/Argentina/Buenos_Aires',
    'CL' => 'America/Santiago',
    'ZA' => 'Africa/Johannesburg',
    'EG' => 'Africa/Cairo',
];
